-- Asha Coach — initial schema
-- Models: coaches, teams, players, parent/guardians, sessions, and the
-- auto-generated parent update that fires every time a coach logs a session.
--
-- Personas all fit this one model:
--   * Club coach: many teams, many players
--   * Team coach: one team, many players
--   * 1:1 private coach: players with team_id = NULL (linked directly via coach)

-- ---------------------------------------------------------------------------
-- Profiles: one row per auth user, tagged with a role.
-- ---------------------------------------------------------------------------
create type user_role as enum ('coach', 'parent', 'admin');

create table profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  role        user_role not null default 'coach',
  full_name   text,
  avatar_url  text,
  push_token  text,                       -- Expo push token for notifications
  created_at  timestamptz not null default now()
);

-- Auto-create a profile row when a new auth user signs up.
create function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce((new.raw_user_meta_data ->> 'role')::user_role, 'coach')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------------
-- Teams (optional grouping). A 1:1 coach may never create one.
-- ---------------------------------------------------------------------------
create table teams (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid not null references profiles (id) on delete cascade,
  name        text not null,
  age_group   text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Players. team_id NULL = standalone (1:1) player.
-- ---------------------------------------------------------------------------
create table players (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid not null references profiles (id) on delete cascade,
  team_id     uuid references teams (id) on delete set null,
  full_name   text not null,
  date_of_birth date,
  position    text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Guardians: links a parent profile to a player (many-to-many).
-- ---------------------------------------------------------------------------
create table player_guardians (
  player_id    uuid not null references players (id) on delete cascade,
  guardian_id  uuid not null references profiles (id) on delete cascade,
  relationship text,
  created_at   timestamptz not null default now(),
  primary key (player_id, guardian_id)
);

-- ---------------------------------------------------------------------------
-- Sessions: the core record. One per time the coach works with a player.
-- ---------------------------------------------------------------------------
create table sessions (
  id            uuid primary key default gen_random_uuid(),
  coach_id      uuid not null references profiles (id) on delete cascade,
  player_id     uuid not null references players (id) on delete cascade,
  session_date  date not null default current_date,
  focus_areas   text[] not null default '{}',     -- e.g. {dribbling, first-touch}
  notes         text,                              -- coach's note to the parent
  rating        smallint check (rating between 1 and 5),
  next_focus    text,
  media_urls    text[] not null default '{}',      -- Supabase Storage paths
  created_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Parent updates: the message a guardian sees/receives per session.
-- Auto-generated by the trigger below — the heart of the product.
-- ---------------------------------------------------------------------------
create table parent_updates (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references sessions (id) on delete cascade,
  player_id    uuid not null references players (id) on delete cascade,
  guardian_id  uuid not null references profiles (id) on delete cascade,
  read_at      timestamptz,
  created_at   timestamptz not null default now()
);

-- Fan out: when a session is logged, create one update per guardian.
create function fan_out_parent_updates()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.parent_updates (session_id, player_id, guardian_id)
  select new.id, new.player_id, pg.guardian_id
  from public.player_guardians pg
  where pg.player_id = new.player_id;
  return new;
end;
$$;

create trigger on_session_created
  after insert on sessions
  for each row execute function fan_out_parent_updates();

-- ---------------------------------------------------------------------------
-- Invites: a coach invites a parent to claim a player.
-- ---------------------------------------------------------------------------
create table invites (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid not null references profiles (id) on delete cascade,
  player_id   uuid not null references players (id) on delete cascade,
  code        text not null unique default encode(gen_random_bytes(6), 'hex'),
  email       text,
  claimed_by  uuid references profiles (id) on delete set null,
  claimed_at  timestamptz,
  expires_at  timestamptz not null default now() + interval '30 days',
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table profiles         enable row level security;
alter table teams            enable row level security;
alter table players          enable row level security;
alter table player_guardians enable row level security;
alter table sessions         enable row level security;
alter table parent_updates   enable row level security;
alter table invites          enable row level security;

-- profiles: read/update your own row
create policy "own profile read"   on profiles for select using (auth.uid() = id);
create policy "own profile update" on profiles for update using (auth.uid() = id);

-- teams: a coach owns their teams
create policy "coach manages teams" on teams
  for all using (auth.uid() = coach_id) with check (auth.uid() = coach_id);

-- players: coach owns them; guardians can read their linked players
create policy "coach manages players" on players
  for all using (auth.uid() = coach_id) with check (auth.uid() = coach_id);

create policy "guardian reads players" on players
  for select using (
    exists (
      select 1 from player_guardians pg
      where pg.player_id = players.id and pg.guardian_id = auth.uid()
    )
  );

-- player_guardians: coach of the player manages links; guardian reads own
create policy "coach manages guardians" on player_guardians
  for all using (
    exists (select 1 from players p
            where p.id = player_guardians.player_id and p.coach_id = auth.uid())
  )
  with check (
    exists (select 1 from players p
            where p.id = player_guardians.player_id and p.coach_id = auth.uid())
  );

create policy "guardian reads own links" on player_guardians
  for select using (guardian_id = auth.uid());

-- sessions: coach manages; guardians read sessions for their players
create policy "coach manages sessions" on sessions
  for all using (auth.uid() = coach_id) with check (auth.uid() = coach_id);

create policy "guardian reads sessions" on sessions
  for select using (
    exists (
      select 1 from player_guardians pg
      where pg.player_id = sessions.player_id and pg.guardian_id = auth.uid()
    )
  );

-- parent_updates: guardian reads/updates own; coach reads updates they generated
create policy "guardian reads updates" on parent_updates
  for select using (guardian_id = auth.uid());

create policy "guardian marks read" on parent_updates
  for update using (guardian_id = auth.uid()) with check (guardian_id = auth.uid());

create policy "coach reads own updates" on parent_updates
  for select using (
    exists (select 1 from sessions s
            where s.id = parent_updates.session_id and s.coach_id = auth.uid())
  );

-- invites: coach manages own; anyone signed-in can read by code to claim
create policy "coach manages invites" on invites
  for all using (auth.uid() = coach_id) with check (auth.uid() = coach_id);
